environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      TOX_ENV: "py27-install-extensions,py27-disable-extensions,py27-without-extensions"

    - PYTHON: "C:\\Python34-x64"
      TOX_ENV: "py34-disable-extensions"

    - PYTHON: "C:\\Python35-x64"
      TOX_ENV: "py35-install-extensions,py35-disable-extensions,py35-without-extensions"

    - PYTHON: "C:\\Python36-x64"
      TOX_ENV: "py36-install-extensions,py36-disable-extensions,py36-without-extensions"

    - PYTHON: "C:\\Python37-x64"
      TOX_ENV: "py37-install-extensions,py37-disable-extensions,py37-without-extensions"

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"

build: false

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"
